
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('joinTable').del()
    .then(function () {
      // Inserts seed entries
      return knex('joinTable').insert([
        {recipes_id: 1, ingredients_id: 1, quantity: 1, label:'grams'},
        {recipes_id: 1, ingredients_id: 2,quantity: 2, label:'cups'},
        {recipes_id: 1, ingredients_id: 3,quantity: 19, label:'ounces'},
        {recipes_id: 1, ingredients_id: 4,quantity: 4, label:'stones'},
        {recipes_id: 1, ingredients_id: 5,quantity: 5, label:'grams'},
        {recipes_id: 2, ingredients_id: 1,quantity: 7, label:'grams'},
        {recipes_id: 2, ingredients_id: 2,quantity: 8, label:'grams'},
        {recipes_id: 2, ingredients_id: 3,quantity: 9, label:'grams'},
        {recipes_id: 2, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 2, ingredients_id: 5,quantity: 1, label:'grams'},
        {recipes_id: 2, ingredients_id: 6,quantity: 1, label:'grams'},
        {recipes_id: 3, ingredients_id: 7,quantity: 1, label:'grams'},
        {recipes_id: 3, ingredients_id: 8,quantity: 1, label:'grams'},
        {recipes_id: 3, ingredients_id: 9,quantity: 1, label:'grams'},
        {recipes_id: 3, ingredients_id: 0,quantity: 1, label:'grams'},
        {recipes_id: 4, ingredients_id: 8,quantity: 1, label:'grams'},
        {recipes_id: 4, ingredients_id: 9,quantity: 1, label:'grams'},
        {recipes_id: 4, ingredients_id: 10,quantity: 1, label:'grams'},
        {recipes_id: 5, ingredients_id: 8,quantity: 1, label:'grams'},
        {recipes_id: 0, ingredients_id: 9,quantity: 1, label:'grams'},
        {recipes_id: 0, ingredients_id: 11,quantity: 1, label:'grams'},
        {recipes_id: 6, ingredients_id: 12,quantity: 1, label:'grams'},
        {recipes_id: 6, ingredients_id: 13,quantity: 1, label:'grams'},
        {recipes_id: 6, ingredients_id: 14,quantity: 1, label:'grams'},
        {recipes_id: 6, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 7, ingredients_id: 12,quantity: 1, label:'grams'},
        {recipes_id: 7, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 7, ingredients_id: 2,quantity: 1, label:'grams'},
        {recipes_id: 7, ingredients_id: 3,quantity: 1, label:'grams'},
        {recipes_id: 7, ingredients_id: 6,quantity: 1, label:'grams'},
        {recipes_id: 8, ingredients_id: 12,quantity: 1, label:'grams'},
        {recipes_id: 8, ingredients_id: 13,quantity: 1, label:'grams'},
        {recipes_id: 8, ingredients_id: 14,quantity: 1, label:'grams'},
        {recipes_id: 8, ingredients_id: 16,quantity: 1, label:'grams'},
        {recipes_id: 8, ingredients_id: 3,quantity: 1, label:'grams'},
        {recipes_id: 9, ingredients_id: 12,quantity: 1, label:'grams'},
        {recipes_id: 9, ingredients_id: 14,quantity: 1, label:'grams'},
        {recipes_id: 9, ingredients_id: 15,quantity: 1, label:'grams'},
        {recipes_id: 9, ingredients_id: 5,quantity: 1, label:'grams'},
        {recipes_id: 10, ingredients_id: 16,quantity: 1, label:'grams'},
        {recipes_id: 10, ingredients_id: 17,quantity: 1, label:'grams'},
        {recipes_id: 10, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 11, ingredients_id: 16,quantity: 1, label:'grams'},
        {recipes_id: 11, ingredients_id: 17,quantity: 1, label:'grams'},
        {recipes_id: 11, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 11, ingredients_id: 6,quantity: 1, label:'grams'},
        {recipes_id: 12, ingredients_id: 18,quantity: 1, label:'grams'},
        {recipes_id: 12, ingredients_id: 19,quantity: 1, label:'grams'},
        {recipes_id: 12, ingredients_id: 20,quantity: 1, label:'grams'},
        {recipes_id: 12, ingredients_id: 8,quantity: 1, label:'grams'},
        {recipes_id: 12, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 12, ingredients_id: 3,quantity: 1, label:'grams'},
        {recipes_id: 13, ingredients_id: 2,quantity: 1, label:'grams'},
        {recipes_id: 13, ingredients_id: 3,quantity: 1, label:'grams'},
        {recipes_id: 13, ingredients_id: 20,quantity: 1, label:'grams'},
        {recipes_id: 13, ingredients_id: 22,quantity: 1, label:'grams'},
        {recipes_id: 13, ingredients_id: 8,quantity: 1, label:'grams'},
        {recipes_id: 13, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 2,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 3,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 4,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 8,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 18,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 19,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 22,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 21,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 16,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 24,quantity: 1, label:'grams'},
        {recipes_id: 14, ingredients_id: 15,quantity: 1, label:'grams'},
        {recipes_id: 15, ingredients_id: 21,quantity: 1, label:'grams'},
        {recipes_id: 15, ingredients_id: 22,quantity: 1, label:'grams'},
        {recipes_id: 15, ingredients_id: 23,quantity: 1, label:'grams'},
        {recipes_id: 16, ingredients_id: 24,quantity: 1, label:'grams'},
        {recipes_id: 16, ingredients_id: 23,quantity: 1, label:'grams'},
        {recipes_id: 16, ingredients_id: 22,quantity: 1, label:'grams'},
        {recipes_id: 17, ingredients_id: 22,quantity: 1, label:'grams'},
        {recipes_id: 17, ingredients_id: 23,quantity: 1, label:'grams'},


      ]);
    });
};